FROM python:3.12-slim
# base image

RUN apt-get update && apt-get install -y --no-install-recommends \
    libgl1 \
    libglib2.0-0 \
    ffmpeg \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app 
# this operation creates app folder in docker image and it changes directory to app

# installs uv pacakge manager and copies uv,uvx into bin folder
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY pyproject.toml uv.lock ./

RUN uv sync --frozen --no-dev 
# frozen installs exactly what's in uv.lock
# no-dev skips development dependecies (pytest,ruff,etc)

# copies code from src folder to apps (docker image) src folder which gets created by docker
COPY src/ ./src/ 

COPY backend/ ./backend/

EXPOSE 8000
# tells docker which port the container application uses

ENV PYTHONUNBUFFERED=1
# sets env variable inside container that tells Python to print logs immediately instead of buffering them

CMD ["uv","run","uvicorn","backend.app:app","--host","0.0.0.0","--port","8000"]
