FROM python:3.12-slim

WORKDIR /app

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev

EXPOSE 8501

COPY src/ ./src/

COPY dashboard/ ./dashboard

EXPOSE 8501 
ENV PYTHONUNBUFFERED=1


CMD ["uv", "run", "streamlit", "run", "dashboard/app.py", \
     "--server.headless=true", \
     "--server.address=0.0.0.0", \
     "--server.port=8501", \
     "--browser.gatherUsageStats=false"]
